[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200

[env:nucleo_f446re_uart_protocol]
extends = env:nucleo_f446re
build_flags =
    -DSTM_UART_PROTOCOL_TEST
